spring:
  application:
    name: auth-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: example@gmail.com
    password: your password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:mysql://localhost:3306/mravel_auth?useSSL=false&serverTimezone=UTC
    username: root
    password: your password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8081

jwt:
  secret: my-super-secret-jwt-key-1234567890
  expiration: 7200000
  refresh-expiration: 1209600000
