spring:
  application:
    name: catalog-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: example@gmail.com
    password: your-mail-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    mongodb:
      uri: mongodb://localhost:27017/mravel_catalog

  jackson:
    default-property-inclusion: non_null

server:
  port: 8083

jwt:
  secret: your-jwt-secret
  expiration: 3600000