"""Convert an approved PlanDraft into a real plan via plan-service.

This is the only place in `ai-plan-service` that performs writes, and it always
runs behind an explicit `POST .../approve` call. Each plan-service write carries
an idempotency key derived from the draft id so retries do not duplicate entities.

Idempotency keys are 36-char UUIDs (uuid5 over a deterministic seed) so they
fit plan-service's `operation_id` column.
"""

import json
import logging
import uuid
from typing import Any, Dict, List
from uuid import uuid4

from app.clients.plan_client import PlanClient
from app.models.session import DraftActivity, PlanDraft
from app.services.catalog_location import catalog_location_fields

# Deterministic namespace for idempotency UUID5. Any constant UUID works.
_IDEM_NAMESPACE = uuid.UUID("8c2a9f55-1d8d-4f4b-9c2a-3f4bbf5d2f01")


def _idem_key(seed: str) -> str:
    return str(uuid.uuid5(_IDEM_NAMESPACE, seed))


def _ordered_day_lists(board: Dict[str, Any]) -> List[Dict[str, Any]]:
    """Extract the DAY lists from a BoardResponse, in chronological/board order.

    plan-service seeds them at positions 0..N-1 (TRASH sits last); we sort by
    `position` then `dayDate` so draft day i maps to the i-th seeded day list.
    """
    lists = board.get("lists") if isinstance(board, dict) else None
    if not isinstance(lists, list):
        return []
    day_lists = [x for x in lists if isinstance(x, dict) and x.get("type") == "DAY"]
    day_lists.sort(
        key=lambda x: (
            x.get("position") if x.get("position") is not None else 9999,
            x.get("dayDate") or "",
        )
    )
    return day_lists

logger = logging.getLogger("ai_plan.approval")


class ApprovalService:
    def __init__(self, plan_client: PlanClient) -> None:
        self._plan_client = plan_client

    async def approve(self, draft: PlanDraft, bearer_token: str) -> Dict[str, Any]:
        plan_body = {
            "title": draft.summary or f"AI Plan - {draft.destination}",
            "description": f"Generated by AI Plan Agent (draft {draft.draft_id})",
            "startDate": draft.start_date.isoformat(),
            "endDate": draft.end_date.isoformat(),
            "destinations": [{"name": draft.destination}] if draft.destination else [],
            "visibility": "PRIVATE",
            "budgetCurrency": draft.budget_currency,
            "budgetTotal": draft.estimated_total_cost_vnd,
            "budgetPerPerson": (
                draft.estimated_total_cost_vnd // draft.travelers if draft.travelers else 0
            ),
        }
        plan = await self._plan_client.create_plan(bearer_token, plan_body)
        plan_id = plan.get("id")
        if not plan_id:
            raise RuntimeError("plan-service did not return a plan id")

        # plan-service auto-seeds ONE DAY list per day in [startDate, endDate] at
        # create time. So we do NOT create lists (that appended a phantom 5th day
        # and returned a null id) — instead we read the board and attach cards to
        # the pre-seeded DAY lists, matched to draft days by chronological order.
        board = await self._plan_client.get_board(bearer_token, plan_id)
        day_lists = _ordered_day_lists(board)
        if len(day_lists) < len(draft.days):
            logger.warning(
                "plan %s seeded %d day lists but draft has %d days — extra days will be skipped",
                plan_id,
                len(day_lists),
                len(draft.days),
            )

        operation_log: List[Dict[str, Any]] = []
        for index, day in enumerate(draft.days):
            if index >= len(day_lists):
                break
            list_id = day_lists[index].get("id")
            if not list_id:
                logger.error(
                    "board list missing id for day %s: %s", day.day_index, day_lists[index]
                )
                raise RuntimeError(
                    f"plan-service board returned a day list without an id (day {day.day_index})"
                )

            # Seeded lists carry a generic title; rename to the draft's day title so
            # the board reads "Ngày 1 — …" rather than "Danh sách hoạt động".
            if day.title:
                try:
                    await self._plan_client.rename_list(bearer_token, plan_id, list_id, day.title)
                except Exception as exc:  # noqa: BLE001 — cosmetic, never fail approval
                    logger.warning("rename_list failed (day %s): %s", day.day_index, exc)
            operation_log.append({"op": "use_list", "list_id": list_id, "day": day.day_index})

            for position, activity in enumerate(day.activities):
                card_idem = _idem_key(f"plan:{plan_id}:card:{day.day_index}:{position}")
                card_body = _activity_to_card_body(activity, draft.travelers)
                try:
                    await self._plan_client.create_card(
                        bearer_token, plan_id, list_id, card_body, idempotency_key=card_idem
                    )
                except Exception as exc:  # noqa: BLE001
                    logger.error(
                        "create_card failed: day=%s position=%s title=%s err=%s",
                        day.day_index,
                        position,
                        activity.title,
                        exc,
                    )
                    raise RuntimeError(
                        f"Không tạo được card '{activity.title}' (ngày {day.day_index}, "
                        f"vị trí {position + 1}): {exc}"
                    ) from exc
                operation_log.append(
                    {"op": "create_card", "idempotency_key": card_idem, "day": day.day_index}
                )

        logger.info(
            "approved draft %s as plan %s with %d ops", draft.draft_id, plan_id, len(operation_log)
        )
        return {"plan_id": plan_id, "operations": operation_log}


def _activity_to_card_body(activity: DraftActivity, travelers: int = 1) -> Dict[str, Any]:
    """Build a CreateCardRequest body. `activityDataJson` holds the AI-specific
    metadata (recommendation + structured fields) so the frontend can render
    address/note/route badges, while plan-service stays agnostic to those.

    Cost is sent both as a total (`cost.estimatedCost`) and as a per-unit breakdown
    (`activityData.ticketPrice` × `ticketCount`) so the card shows the right
    "giá/lượt" and "số lượt/người tham gia" instead of defaulting to 1 person."""

    travelers = max(1, travelers)
    quantity = max(1, activity.quantity or 1)
    unit_price = activity.unit_price_vnd
    if unit_price is None and activity.estimated_cost_vnd:
        unit_price = activity.estimated_cost_vnd // quantity

    activity_data: Dict[str, Any] = {
        "reason": activity.reason,
        "locationName": activity.location_name,
        "address": activity.address,
        "note": activity.note,
        "routeHint": activity.route_hint,
        "distanceText": activity.distance_text,
        "transportMode": activity.transport_mode,
        "ticketPrice": unit_price,
        "ticketCount": quantity,
    }
    # Drop None to keep the JSON lean.
    activity_data = {k: v for k, v in activity_data.items() if v}

    if activity.recommendation:
        rec = activity.recommendation
        activity_data["recommendation"] = {
            "kind": rec.catalog_kind,
            "id": rec.catalog_id,
            "slug": rec.catalog_slug,
            "name": rec.name,
            "latitude": rec.latitude,
            "longitude": rec.longitude,
            "coverImageUrl": rec.cover_image_url,
            "avgRating": rec.avg_rating,
        }
        # Mirror a manual place pick so the FE modal pre-fills the name + location and
        # the picker auto-focuses this catalog item (hotelLocation/restaurantLocation/…).
        activity_data.update(
            catalog_location_fields(
                activity.activity_type.value,
                activity_data["recommendation"],
                address=activity.address,
            )
        )

    # Compose a richer human-readable description with address/note when available,
    # so the card body shows useful info even before the frontend renders the JSON.
    description_parts = []
    if activity.description:
        description_parts.append(activity.description)
    if activity.address:
        description_parts.append(f"📍 {activity.address}")
    if activity.note:
        description_parts.append(f"💡 {activity.note}")
    if activity.route_hint:
        route_line = f"🗺️ {activity.route_hint}"
        if activity.distance_text:
            route_line += f" ({activity.distance_text})"
        if activity.transport_mode:
            route_line += f" — {activity.transport_mode}"
        description_parts.append(route_line)
    description = "\n".join(description_parts)

    body: Dict[str, Any] = {
        "text": activity.title,
        "description": description,
        "activityType": activity.activity_type.value,
        "activityDataJson": json.dumps(activity_data, ensure_ascii=False),
        "durationMinutes": activity.duration_minutes,
        # Trip headcount so each card shows "👥 N người" (CardDto.participantCount).
        "participantCount": travelers,
    }
    if activity.start_time:
        body["startTime"] = _normalize_time(activity.start_time)
    if activity.end_time:
        body["endTime"] = _normalize_time(activity.end_time)
    if activity.estimated_cost_vnd:
        body["cost"] = {
            "currencyCode": "VND",
            "estimatedCost": activity.estimated_cost_vnd,
            "participantCount": travelers,
        }
    return body


def fresh_idempotency_key() -> str:
    return str(uuid4())


def _normalize_time(value: str) -> str:
    """Plan-service deserialises LocalTime via `HH:mm` or `HH:mm:ss`. We send
    `HH:mm` with leading zeros; "9:00" → "09:00". Returns the input if it
    already looks normalized or if it can't be parsed."""
    if not isinstance(value, str):
        return value
    parts = value.split(":")
    if len(parts) < 2:
        return value
    try:
        hh = int(parts[0])
        mm = int(parts[1])
    except ValueError:
        return value
    return f"{hh:02d}:{mm:02d}"
