server:
  port: 8082

spring:
  application:
    name: user-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME:${MYSQL_USER:root}}
    password: ${SPRING_DATASOURCE_PASSWORD:${MYSQL_ROOT_PASSWORD}}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

mravel:
  plan-service:
    url: http://gateway:8080
  notification-service:
    url: http://gateway:8080
    create-path: /api/notifications
