package com.mravel.catalog.model.enums;

public enum TagType {
    AMENITY,    // wifi, parking, pool, breakfast...
    FEATURE,    // family-friendly, pet-friendly...
    CUISINE,    // Vietnamese, Italian...
    SERVICE     // thuê xe máy, đưa đón sân bay...
}